name: Run Tests and Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build_and_test_monorepo:
    runs-on: ubuntu-latest

    name: Build and test monorepo

    steps:
    - uses: actions/checkout@v3

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPCS
      run: composer run-script lint

    - name: Run unit test suite with code coverage
      run: composer run-script test-coverage

  after_split_testing:
    needs: build_and_test_monorepo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package_path:
          - framework/foundation
          - framework/infrastructure
          - framework/test-utils
          - product/core
          - product/core-data-sql
          - product/core-test-utils

    name: After Split Testing of ${{ matrix.package_path }}

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - name: Install monorepo composer
        run: composer install --no-progress
      - name: Update package composer path
        run: vendor/bin/monorepo-builder localize-composer-paths packages/${{ matrix.package_path }}/composer.json
      - run: cd packages/${{ matrix.package_path }}
      - name: Install package composer
        run: composer update --no-progress
      - name: Run package tests
        run: composer test
